# Generated by Django 5.2.8 on 2025-11-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_score_alter_resume_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='parsed_text',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='resume',
            name='top_job_titles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
