# Generated by Django 5.2.8 on 2025-11-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_resume_parsed_text_remove_resume_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='top_job_titles',
        ),
        migrations.AddField(
            model_name='resume',
            name='parsed_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
